name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build ESP32 firmware
      run: pio run -e lolin_d32
    
    - name: Build ESP32-S3 firmware
      run: pio run -e esp32-s3-devkitc-1
    
    - name: Prepare release files
      run: |
        cp .pio/build/lolin_d32/firmware.bin esp32_firmware.bin
        cp .pio/build/esp32-s3-devkitc-1/firmware.bin esp32_s3_firmware.bin
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .pio/build/lolin_d32/firmware.bin
          .pio/build/esp32-s3-devkitc-1/firmware.bin
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}